// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy-bwcyJUL9vaYKBP3UYQkJ5D5R2yv8bI',
    appId: '1:451202152728:web:150b3af172985945d8c66d',
    messagingSenderId: '451202152728',
    projectId: 'chattingapp-93976',
    authDomain: 'chattingapp-93976.firebaseapp.com',
    storageBucket: 'chattingapp-93976.firebasestorage.app',
    measurementId: 'G-XRL0QFMN18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj2Ym1se5P5rLmFy18DVaB9GQEhrNrOB8',
    appId: '1:451202152728:android:10d4b4db28a9bd63d8c66d',
    messagingSenderId: '451202152728',
    projectId: 'chattingapp-93976',
    storageBucket: 'chattingapp-93976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyDLbpeTyZpDGNP0SW6bGWeqYQz-VsKco',
    appId: '1:451202152728:ios:48a2dbabec44fd5dd8c66d',
    messagingSenderId: '451202152728',
    projectId: 'chattingapp-93976',
    storageBucket: 'chattingapp-93976.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyDLbpeTyZpDGNP0SW6bGWeqYQz-VsKco',
    appId: '1:451202152728:ios:48a2dbabec44fd5dd8c66d',
    messagingSenderId: '451202152728',
    projectId: 'chattingapp-93976',
    storageBucket: 'chattingapp-93976.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy-bwcyJUL9vaYKBP3UYQkJ5D5R2yv8bI',
    appId: '1:451202152728:web:9d660e1027b9b1c9d8c66d',
    messagingSenderId: '451202152728',
    projectId: 'chattingapp-93976',
    authDomain: 'chattingapp-93976.firebaseapp.com',
    storageBucket: 'chattingapp-93976.firebasestorage.app',
    measurementId: 'G-QWBH2YFVMN',
  );
}
